import Link from "next/link";
import Image from "next/image";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href={"/"}>Home</Link>
          <Link href={"/post"}>Posts</Link>
          <Link href={"/write"}>Write</Link>
          {/* <Image
            src="https://picsum.photos/200/300"
            alt="d"
            width="200"
            height="300"
          /> */}
        </div>
        {children}
      </body>
    </html>
  );
}
